version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow-webserver
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow_password@postgres:5432/airflow_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__RBAC: "True"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow_password@postgres:5432/airflow_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    depends_on:
      - postgres
    networks:
      - airflow_network

  airflow-worker:
    image: apache/airflow:2.7.1
    container_name: airflow-worker
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow_password@postgres:5432/airflow_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    depends_on:
      - postgres
    networks:
      - airflow_network

  streamlit:
    image: python:3.9-slim
    container_name: streamlit
    volumes:
      - ./src:/app
    command: streamlit run /app/data_visualization.py
    ports:
      - "8501:8501"
    networks:
      - airflow_network

volumes:
  postgres_data:

networks:
  airflow_network:
    driver: bridge
